//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_emp_240424.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int id { get; set; }
        public int roll { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string gender { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
    }
}
