//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_emp_240424.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> salary { get; set; }
    
        public virtual tblEmp tblEmp { get; set; }
    }
}
